
services:
  php:
    build: .
    volumes:
      - ./api/:/var/www/html
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    image: docker.io/nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./api/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: docker.io/mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: