
services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      - mysql

  nginx:
    image: docker.io/nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

